# Generated by Django 3.2.12 on 2022-05-25 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_score',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
